// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/architecture-diagram/ArchDiagram.tsx": () => import("../components/mockups/architecture-diagram/ArchDiagram.tsx"),
  "./components/mockups/gitlab-mr-flow/GitLabMRFlow.tsx": () => import("../components/mockups/gitlab-mr-flow/GitLabMRFlow.tsx")
};
